# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [5]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [17]:
# 1. Shape, number of dimensions, and type of elements
shape = nparr.shape  # (12, 6)
num_dimensions = nparr.ndim  # 2
element_type = nparr.dtype  # int64

# 2. Standard deviation of all elements
std_dev = np.std(nparr)  # Standard deviation of all elements in nparr

# 3. Position of the maximum value element
max_position = np.argmax(nparr)  # Index of the maximum value in flattened array

# 4. Array of zeros with the same shape
zeros_array = np.zeros(nparr.shape)  # An array of the same shape, filled with zeros

# 5. Array of ones with the same shape
ones_array = np.ones(nparr.shape)  # An array of the same shape, filled with ones

# 6. Array of square root values
sqrt_array = np.sqrt(nparr)  # An array of the square roots of each element in nparr

# 7. Matrix multiplication with transpose
result = np.dot(nparr, nparr.T)  # Matrix multiplication of nparr with its transpose

# Results

print(f"Shape of nparr: {shape}")  # (12, 6)

print(f"Number of dimensions of nparr: {num_dimensions}")  # 2

print(f"Type of elements in nparr: {element_type}")  # int64

print(f"Standard deviation of elements in nparr: {std_dev}")  # float64 value

print(f"Position of maximum value in nparr: {max_position}")  # index (flattened)

# Arrays
print(f"Array of zeros with the same shape:\n{zeros_array}")

print(f"Array of ones with the same shape:\n{ones_array}")

print(f"Array of square root values:\n{sqrt_array}")

print(f"Result of matrix multiplication with transpose (12x12 array):\n{result}")


Shape of nparr: (12, 6)
Number of dimensions of nparr: 2
Type of elements in nparr: int64
Standard deviation of elements in nparr: 20.7826049057058
Position of maximum value in nparr: 71
Array of zeros with the same shape:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Array of ones with the same shape:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Array of square root values:
[[12.04159458 12.08304597 12.12435565 12.16552506 12.20655562 12.24744871]
 [12.28820573 12.32882801 12.36931688 12.40967365 12.4498996  12.489996  ]
 [12.52996409 12.56980509 12.60952021 12.64911064 12.6885

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [15]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)
# 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than 10,000

traffic = a_df[a_df['cnt'] > 10000]
high_traffic_rows = traffic.shape[0]

print(f"Number of rows with traffic higher than 10,000: {high_traffic_rows:,}")

# 2. Print the names of all the columns of the dataframe

print(f"Columns in the dataframe: {', '.join(a_df.columns)}")

# 3. Print a subset of the dataframe containing the 10th and the 3rd rows (in that order)

subset_rows = a_df.iloc[[9, 2]]  # 10th row is index 9, 3rd row is index 2
print("\nSubset of 10th and 3rd rows:")

print(subset_rows)

# 4. Which US state has the 8th largest total airport traffic?

state_traffic = a_df.groupby('state')['cnt'].sum().sort_values(ascending=False)
largest_state = state_traffic.index[7]  # 8th largest will be at index 7 (0-based index)

print(f"\nThe US state with the 8th largest total airport traffic: {largest_state}")

# 5. Which state has the second-most total number of airports?

airports_count = a_df.groupby('state').size().sort_values(ascending=False)
second_most = airports_count.index[1]  # second-most will be at index 1

print(f"\nThe US state with the second-most total number of airports: {second_most}")

# 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?

city_traffic = a_df.groupby('city')['cnt'].sum()
multiple_airports = city_traffic[city_traffic > 10000]
least_traffic_city = multiple_airports.idxmin()  # city with the least total traffic

print(f"\nThe city with multiple airports having the least total traffic: {least_traffic_city}")

# 7. What is the total airport traffic for all states that border the state of Massachusetts?

bordering_states = ['New York', 'Vermont', 'New Hampshire', 'Connecticut', 'Rhode Island']
border_states_traffic = a_df[a_df['state'].isin(bordering_states)]['cnt'].sum()

print(f"\nTotal airport traffic for all states bordering Massachusetts: {border_states_traffic:,}")


Number of rows with traffic higher than 10,000: 10
Columns in the dataframe: iata, airport, city, state, country, lat, long, cnt

Subset of 10th and 3rd rows:
  iata                          airport               city state country  \
9  CLT  Charlotte/Douglas International          Charlotte    NC     USA   
2  DFW  Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   

         lat       long    cnt  
9  35.214011 -80.943126  10490  
2  32.895951 -97.037200  20662  

The US state with the 8th largest total airport traffic: CO

The US state with the second-most total number of airports: TX

The city with multiple airports having the least total traffic: Charlotte

Total airport traffic for all states bordering Massachusetts: 0
